# Generated by Django 2.1.4 on 2019-01-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('past_path', models.CharField(max_length=200)),
                ('post_category', models.CharField(max_length=100)),
            ],
        ),
    ]
