# Generated by Django 2.1.4 on 2019-01-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsing',
            old_name='past_path',
            new_name='post_path',
        ),
    ]
