# Generated by Django 2.1.4 on 2019-01-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_app', '0002_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.RemoveField(
            model_name='box',
            name='mylist',
        ),
        migrations.AddField(
            model_name='box',
            name='mylist',
            field=models.ManyToManyField(to='crawler_app.crawl'),
        ),
    ]
