# Generated by Django 2.1.4 on 2019-01-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_app', '0003_auto_20190105_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='title',
        ),
        migrations.RemoveField(
            model_name='box',
            name='mylist',
        ),
        migrations.AddField(
            model_name='box',
            name='mylist',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
