# Generated by Django 2.1.4 on 2019-01-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_app', '0006_auto_20190105_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='mylist',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
